steps:

- name: gcr.io/cloud-builders/docker
  args: [ build, -t, gcr.io/emc-ema-mockrobot-d/test1, . ]

- name: gcr.io/cloud-builders/docker
  args: [push, gcr.io/emc-ema-mockrobot-d/test1]  

- name: gcr.io/cloud-builders/gcloud
  args: [ compute, ssh, emc-ema-mockrobot-d, --zone, us-central1-a, --command, "sudo docker pull gcr.io/emc-ema-mockrobot-d/test1 && sudo docker run gcr.io/emc-ema-mockrobot-d/test1:latest"]

  
# images:
# - gcr.io/emc-ema-mockrobot-d/test1
