steps:

- name: gcr.io/cloud-builders/docker
  args: [ build, -t, gcr.io/emc-ema-mockrobot-d/gcp-cloudbuild-gce-angular, . ]

- name: gcr.io/cloud-builders/gcloud
  args: [ compute, ssh, emc-ema-mockrobot-d, --zone, us-central1-a, --command, "sleep 60 && sudo docker pull gcr.io/emc-ema-mockrobot-d/gcp-cloudbuild-gce-angular"]

  
images:
- gcr.io/emc-ema-mockrobot-d/gcp-cloudbuild-gce-angular
