steps:

# - name: gcr.io/cloud-builders/docker
  # args: [ build, -t, gcr.io/emc-ema-mockrobot-d/gcp-cloudbuild-gce-angular, . ]

# - name: gcr.io/cloud-builders/gcloud
#   args: [ compute, instance-groups, managed, rolling-action, restart, gce-angular-instance-group, --zone=us-central1-a  ]

# - name: gcr.io/cloud-builders/gcloud
  # args: [ compute, instances, stop, emc-ema-mockrobot-d-test, --zone=us-central1-a ]

# - name: gcr.io/cloud-builders/gcloud
  # args: [ compute, instances, start, emc-ema-mockrobot-d-test, --zone=us-central1-a ]

# - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  # entrypoint: gcloud
  # args:
    # - "-c"
    # - "compute ssh emc-ema-mockrobot-d --zone us-central1-a  --tunnel-through-iap --command=\"touch ~/wf_$(date +\"\"%Y_%m_%d_%H_%M_%S\"\").log\n"
  # entrypoint: "/bin/sh"

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash' 
  args:
  - "compute ssh emc-ema-mockrobot-d --zone us-central1-a  --tunnel-through-iap --command=\"touch ~/wf_$(date +\"\"%Y_%m_%d_%H_%M_%S\"\").log\n"
  
# images:

# - gcr.io/emc-ema-mockrobot-d/gcp-cloudbuild-gce-angular
